{% set name = "pinentry" %}
{% set version = "1.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/gpg/{{ name }}/archive/refs/tags/{{ name }}-{{ version }}.tar.gz
  sha256: 3cd7e17a3c0008526c28f1ab6a05f865a7ba7d8c5e4af73d7103fbbb25349833

build:
  number: 0
  missing_dso_whitelist:
    - $RPATH/libassuan.9.dylib
    - $RPATH/libgpg-error.0.dylib
    - $RPATH/libncursesw.6.dylib
  skip: True  # [win]
  skip: True  # [s390x]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
    - libtool
    - automake
    - gettext
    - libassuan ==3.0.1
  host:
    - libiconv ==1.16
  run:
    - libassuan ==3.0.1
    - libgpg-error
    - ncurses
    - libiconv ==1.16
    
about:
  home: https://www.gnupg.org/related_software/pinentry/index.html
  summary: Pinentry is a small collection of dialog programs that allow GnuPG to read passphrases and PIN numbers in a secure manner.
  license: GPL-v2
  license_family: GPL
  license_file: COPYING
  description: |
    Pinentry is a small collection of dialog programs that allow GnuPG to read passphrases and PIN numbers in a secure manner. 
    There are versions for the common GTK and Qt toolkits as well as for the text terminal (Curses).
  doc_url: https://www.gnupg.org/related_software/pinentry/index.html
  dev_url: https://github.com/gpg/pinentry

extra:
  recipe-maintainers:
    - aosipov
  skip-lints:
    - missing_tests